//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public long fv_Id { get; set; }
        public long fv_event { get; set; }
        public long fv_owner { get; set; }
        public string fv_comment { get; set; }
        public System.DateTime fv_date { get; set; }
        public string fv_name { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_EVENT
        /// </summary>
        public virtual SportEvent SportEvent { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_OWNER
        /// </summary>
        public virtual UserProfile UserProfile { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + fv_event.GetHashCode();
    			hash = hash * multiplier + fv_owner.GetHashCode();
    			hash = hash * multiplier + (fv_comment == null ? 0 : fv_comment.GetHashCode());
    			hash = hash * multiplier + fv_date.GetHashCode();
    			hash = hash * multiplier + (fv_name == null ? 0 : fv_name.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            Favorite target = obj as Favorite;
    
    		return true
               &&  (this.fv_Id == target.fv_Id )       
               &&  (this.fv_event == target.fv_event )       
               &&  (this.fv_owner == target.fv_owner )       
               &&  (this.fv_comment == target.fv_comment )       
               &&  (this.fv_date == target.fv_date )       
               &&  (this.fv_name == target.fv_name )       
               ;
    
        }
    
    
    	public static bool operator ==(Favorite  objA, Favorite  objB)
        {
            // Check if the objets are the same Favorite entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Favorite  objA, Favorite  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strFavorite = new StringBuilder();
    
    		strFavorite.Append("[ ");
           strFavorite.Append(" fv_Id = " + fv_Id + " | " );       
           strFavorite.Append(" fv_event = " + fv_event + " | " );       
           strFavorite.Append(" fv_owner = " + fv_owner + " | " );       
           strFavorite.Append(" fv_comment = " + fv_comment + " | " );       
           strFavorite.Append(" fv_date = " + fv_date + " | " );       
           strFavorite.Append(" fv_name = " + fv_name + " | " );       
            strFavorite.Append("] ");    
    
    		return strFavorite.ToString();
        }
    
    
    }
}
