//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class GroupUsers
    {
        public GroupUsers()
        {
            this.UsersOnGroup = new HashSet<UserProfile>();
            this.Recommendation = new HashSet<Recommendation>();
        }
    
        public long group_usersId { get; set; }
        public string gr_name { get; set; }
        public string gr_description { get; set; }
        public long gr_owner { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_GroupUsersOwner
        /// </summary>
        public virtual UserProfile UserOwner { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): GroupUsersUserProfile
        /// </summary>
        public virtual ICollection<UserProfile> UsersOnGroup { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): RecommendationGroup
        /// </summary>
        public virtual ICollection<Recommendation> Recommendation { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + (gr_name == null ? 0 : gr_name.GetHashCode());
    			hash = hash * multiplier + (gr_description == null ? 0 : gr_description.GetHashCode());
    			hash = hash * multiplier + gr_owner.GetHashCode();
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            GroupUsers target = obj as GroupUsers;
    
    		return true
               &&  (this.group_usersId == target.group_usersId )       
               &&  (this.gr_name == target.gr_name )       
               &&  (this.gr_description == target.gr_description )       
               &&  (this.gr_owner == target.gr_owner )       
               ;
    
        }
    
    
    	public static bool operator ==(GroupUsers  objA, GroupUsers  objB)
        {
            // Check if the objets are the same GroupUsers entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(GroupUsers  objA, GroupUsers  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strGroupUsers = new StringBuilder();
    
    		strGroupUsers.Append("[ ");
           strGroupUsers.Append(" group_usersId = " + group_usersId + " | " );       
           strGroupUsers.Append(" gr_name = " + gr_name + " | " );       
           strGroupUsers.Append(" gr_description = " + gr_description + " | " );       
           strGroupUsers.Append(" gr_owner = " + gr_owner + " | " );       
            strGroupUsers.Append("] ");    
    
    		return strGroupUsers.ToString();
        }
    
    
    }
}
