//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public Recommendation()
        {
            this.GroupUsers = new HashSet<GroupUsers>();
        }
    
        public long recommendationId { get; set; }
        public long userId { get; set; }
        public long eventId { get; set; }
        public string recommendation_text { get; set; }
        public System.DateTime publishDate { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_Recommendation_EventId
        /// </summary>
        public virtual SportEvent SportEvent { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_RecommendationUserId
        /// </summary>
        public virtual UserProfile UserProfile { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): RecommendationGroup
        /// </summary>
        public virtual ICollection<GroupUsers> GroupUsers { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + userId.GetHashCode();
    			hash = hash * multiplier + eventId.GetHashCode();
    			hash = hash * multiplier + (recommendation_text == null ? 0 : recommendation_text.GetHashCode());
    			hash = hash * multiplier + publishDate.GetHashCode();
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type?
    	    
            Recommendation target = obj as Recommendation;
    
    		return true
               &&  (this.recommendationId == target.recommendationId )       
               &&  (this.userId == target.userId )       
               &&  (this.eventId == target.eventId )       
               &&  (this.recommendation_text == target.recommendation_text )       
               &&  (this.publishDate == target.publishDate )       
               ;
    
        }
    
    
    	public static bool operator ==(Recommendation  objA, Recommendation  objB)
        {
            // Check if the objets are the same Recommendation entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Recommendation  objA, Recommendation  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strRecommendation = new StringBuilder();
    
    		strRecommendation.Append("[ ");
           strRecommendation.Append(" recommendationId = " + recommendationId + " | " );       
           strRecommendation.Append(" userId = " + userId + " | " );       
           strRecommendation.Append(" eventId = " + eventId + " | " );       
           strRecommendation.Append(" recommendation_text = " + recommendation_text + " | " );       
           strRecommendation.Append(" publishDate = " + publishDate + " | " );       
            strRecommendation.Append("] ");    
    
    		return strRecommendation.ToString();
        }
    
    
    }
}
